---

- name: wordle-clone
  docker_container:
    name: wordle-clone
    image: "{{ word_guess_image }}"
    ports:
      - "3210:3000"
    restart_policy: unless-stopped

- name: react-pentago
  docker_container:
    name: react-pentago
    image: "{{ pentago_image }}"
    ports:
      - "3211:3000"
    restart_policy: unless-stopped
