---

- name: ensures loki dir exists
  file:
    path: "{{ docker_path }}/loki"
    state: directory
    
- name: copy loki configuration
  copy:
    src: "configs/metrics/loki-config.yml"
    dest: "{{ docker_path }}/loki/loki-config.yml"

- name: ensures prometheus dir exists
  file:
    path: "{{ docker_path }}/prometheus"
    state: directory
    
- name: copy prometheus configuration
  copy:
    src: "configs/metrics/prometheus.yml"
    dest: "{{ docker_path }}/prometheus/prometheus.yml"

- name: ensure promtail dir exists
  file:
    path: "{{ docker_path }}/promtail"
    state: directory
    
- name: copy promtail configuration
  copy:
    src: "configs/shared/promtail-config.yml"
    dest: "{{ docker_path }}/promtail/promtail-config.yml"

