---

- hosts: main
  vars:
    pip_install_packages:
      - name: docker

  tasks:
    - include_vars: dependencies.yml
    - import_tasks: tasks/main/main.yml

- hosts: network
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - include_vars: dependencies.yml
    - import_tasks: tasks/network/main.yml

