---

- hosts: main
  tasks:
    - import_tasks: tasks/main_configs.yml

- hosts: main
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/main_containers.yml

- hosts: main
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/web_containers.yml

- hosts: network
  tasks:
    - import_tasks: tasks/network_configs.yml

- hosts: network
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/network_containers.yml
