---

- hosts: main
  vars:
    pip_install_packages:
      - name: docker
    ansible_command_timeout: 120
  tasks:
    - import_tasks: tasks/main/main.yml

- hosts: network
  vars:
    pip_install_packages:
      - name: docker
    ansible_command_timeout: 120
  tasks:
    - import_tasks: tasks/network/main.yml

