---
#- hosts: main
#  gather_facts: no
#  tasks:
#    - import_tasks: tasks/main/pre.yml

- hosts: main
  gather_facts: no
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/main/containers.yml

- hosts: web
  gather_facts: no
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/web/containers.yml