---
- hosts: server
  gather_facts: no
  tasks:
    - import_tasks: tasks/pre.yml

- hosts: server
  gather_facts: no
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/containers.yml

