---

- hosts: fragile
  vars:
    pip_install_packages:
      - name: docker
      - name: requests
  tasks:
    - import_tasks: tasks/main/main.yml

- hosts: temescal
  vars:
    pip_install_packages:
      - name: docker
      - name: requests
  tasks:
    - import_tasks: tasks/network/main.yml

- hosts: metrics
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/metrics/main.yml

- hosts: docker
  tasks:
    - import_tasks: tasks/docker_tasks/cron_jobs.yml

