---

- hosts: fragile
  gather_facts: false
  tasks:
    - import_tasks: tasks/fragile_configs.yml
  

- hosts: fragile
  gather_facts: false
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/fragile_containers.yml

- hosts: web
  gather_facts: false
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/web_containers.yml

- hosts: network
  gather_facts: false
  tasks:
    - import_tasks: tasks/network_configs.yml

- hosts: network
  gather_facts: false
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/network_containers.yml
