---
- hosts: main
  gather_facts: no
  tasks:
    - import_tasks: tasks/pre.yml

- hosts: main
  gather_facts: no
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/main_containers.yml

- hosts: web
  gather_facts: no
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/web_containers.yml

- hosts: network
  gather_facts: no
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/network_containers.yml