---

- hosts: main
  vars:
    pip_install_packages:
      - name: docker
      - name: requests
  tasks:
    - import_tasks: tasks/main/main.yml

- hosts: network
  vars:
    pip_install_packages:
      - name: docker
      - name: requests
  tasks:
    - import_tasks: tasks/network/main.yml

- hosts: metrics
  vars:
    pip_install_packages:
      - name: docker
  tasks:
    - import_tasks: tasks/metrics/main.yml

