global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  scrape_timeout:      10s
  evaluation_interval: 60s
  
  # A scrape configuration containing exactly one endpoint to scrape:
  # Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    honor_labels: true
    honor_timestamps: true
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node_main
    honor_labels: true
    scrape_interval: 10s
    scrape_timeout: 9s
    metrics_path: /metrics
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: node_web
    honor_labels: true
    scrape_interval: 10s
    scrape_timeout: 9s
    metrics_path: /metrics
    static_configs:
      - targets: ['10.32.1.12:9100']

  - job_name: 'docker_main'
    static_configs:
      - targets: ['10.32.1.10:9323']
  
  - job_name: 'docker_web'
    static_configs:
      - targets: ['10.32.1.12:9323']
