
--- 

- name: ensures prometheus dir exists
  file:
    path: "{{ docker_path }}/prometheus"
    state: directory
    
- name: copy prometheus configuration
  copy:
    src: "configs/fragile/prometheus.yml"
    dest: "{{ docker_path }}/prometheus/prometheus.yml"

- name: ensures homer dir exists
  file:
    path: "{{ docker_path }}/homer"
    state: directory

- name: copy homer configuration
  ansible:
    src: "configs/homer_config.yml"
    dest: "{{ docker_path }}/homer/config.yml"

