---

- name: create network for grafana, loki, promtail, node_exporter, and prometheus
  docker_network:
    name: metrics

- name: create persistent volume for loki
  docker_volume:
    name: loki_data

# loki
- name: loki
  docker_container:
    name: loki
    image: grafana/loki:2.9.2
    volumes:
      - "loki_data:/etc/loki/"
    ports:
      - "3100:3100"
    networks:
      - name: "metrics"
    restart_policy: unless-stopped

- name: create persistent volume for loki
  docker_volume:
    name: promtail_data

# promtail
- name: promtail
  docker_container:
    name: promtail
    image: grafana/promtail:2.9.2
    volumes:
      - "promtail_data:/etc/promtail"
      - "/var/log:/var/log"
    networks:
      - name: "metrics"
    restart_policy: unless-stopped

# node exporter
- name: node-exporter
  docker_container:
    name: node-exporter
    image: prom/node-exporter@sha256:40ba9ef2dc8d7564d76656feca7f679062d2df71653618211d38c0ec51ebc28c
    command: ["--path.rootfs=/host"]
    ports:
      - "9100:9100"
    volumes:
      - "/:/host:ro,rslave"
    networks:
      - name: "metrics"
    restart_policy: unless-stopped

- name: sensors-exporter
  docker_container:
    name: sensors-exporter
    image: anthonymolinari/sensors-exporter@sha256:13839985e6c2188521528536d539fb77b73f55b38b02480878f8639713d72f17
    ports:
      - "9200:8282"
    networks:
      - name: "metrics"
    restart_policy: unless-stopped

# promestheus
- name: promestheus
  docker_container:
    name: prometheus
    image: prom/prometheus@sha256:01226a3d35f024d806c206e8d10e0bdfb6225c2366e4f8313362b4ae828f72f9
    ports:
      - "9090:9090"
    volumes:
      - "{{ docker_path }}/prometheus:/etc/prometheus"
    networks:
      - name: "metrics"
    restart_policy: unless-stopped

- name: create persistent volume for grafana
  docker_volume:
    name: grafana_data

# grafana
- name: grafana
  docker_container:
    name: grafana
    image: grafana/grafana@sha256:44021e67e80adb3e7dcd71520e58de59dbbfcf0af44c65fe0f0f0d750e80cbb7
    ports:
      - "3000:3000"
    networks:
      - name: "metrics"
    volumes:
      - "grafana_data:/var/lib/grafana"
    restart_policy: unless-stopped

# homer
- name: homer-dashboard
  docker_container:
    name: homer-dashboard
    image: b4bz/homer@sha256:2716c6071ed010a0dc8510ae7896152e645c0a0410f8930340ed0ac11892f49d
    volumes:
      - "{{ docker_path }}/homer:/www/assets"
    ports:
      - "8385:8080"
    restart_policy: unless-stopped


# openbooks
- name: openbooks 
  docker_container:
    name: openbooks
    image: evanbuss/openbooks@sha256:3b3d34d8b77e8261df1f470e1ca8344c035e316a86667dc7c1ab2e768d6359f1
    volumes:
      - "{{downloads_dir}}:/books"
    ports:
      - "4567:80"
    command: ["--name", "iker_neptunus", "--persist", "-s", "irc.irchighway.net:9999"]
    restart_policy: unless-stopped


# plex
- name: plex
  docker_container:
    name: plex
    image: linuxserver/plex@sha256:d125d36cc26129936e429b4c9d0964a729a9a9d21ee5f9a03ac73dd6b7137981
    volumes:
      - "{{ media_dir }}:/Media"
      - "{{ docker_path }}/plex/config:/config"
    network_mode: "host"
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: "docker"
    restart_policy: unless-stopped

# sonarr
- name: sonarr
  docker_container:
    name: sonarr
    image: linuxserver/sonarr@sha256:6c960666882d256b7477838b3c153435e348c0b99b9ec34acf0c5ec23e0b6304
    ports:
      - "8989:8989"
    volumes:
      - "{{ docker_path }}/sonarr/config:/config"
      - "{{ media_dir }}:/tv"
      - "{{ downloads_dir }}/torrents:/downloads"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped

# radarr
- name: radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr@sha256:d72310ac43f8083fed801629afaa6b14c18446d66f6aa272a2216a6133fcb3a7
    ports:
      - "7878:7878"
    volumes:
      - "{{ docker_path }}/radarr/config:/config"
      - "{{ media_dir }}:/movies"
      - "{{ downloads_dir }}/torrents:/downloads"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped


# vpn
# prowlarr
# transmission
# tdarr

