
--- 

- name: ensures prometheus dir exists
  file:
    path: "{{ docker_path }}/prometheus"
    state: directory
    
- name: copy prometheus configuration
  copy:
    src: "configs/main/prometheus.yml"
    dest: "{{ docker_path }}/prometheus/prometheus.yml"

- name: ensures homer dir exists
  file:
    path: "{{ docker_path }}/homer"
    state: directory
  become: true

- name: copy homer configuration
  copy:
    src: "configs/main/homer_config.yml"
    dest: "{{ docker_path }}/main/config.yml"
  become: true

- name: ensures traefik dir exists
  file:
    path: "{{ docker_path }}/traefik"
    state: directory
  become: true

- name: copy traefik configuration
  copy:
    src: "/configs/shared/traefik.yml"
    dest: "{{ docker_path }}/traefik/traefik.yml"