---
# homer
- name: homer-dashboard
  docker_container:
    name: homer-dashboard
    image: b4bz/homer@sha256:23ef711ea0f5681f668930eae7661a8815184afd99885c387b0eef33fe6982b8
    volumes:
      - "{{ docker_path }}/homer:/www/assets"
    ports:
      - "8385:8080"
    restart_policy: unless-stopped

# kanboard
- name: kanboard
  docker_container:
    name: kanboard
    image: kanboard/kanboard@sha256:d3907466c5f063f918813c9a5d41b535d71a9d1a258b4f2eb93a65f633ad0a4b
    volumes: 
      - "{{ docker_path }}/kanboard/data:/var/www/app/data"
      - "{{ docker_path }}/kanboard/plugins:/var/www/app/plugins"
    ports:
      - "8765:8765"
    restart_policy: unless-stopped

# openbooks
- name: openbooks 
  docker_container:
    name: openbooks
    image: evanbuss/openbooks@sha256:3b3d34d8b77e8261df1f470e1ca8344c035e316a86667dc7c1ab2e768d6359f1
    volumes:
      - "{{downloads_dir}}:/books"
    command: ["--name", "iker_neptunus", "--persist", "-s", "irc.irchighway.net:9999"]
    restart_policy: unless-stopped

# plex
- name: plex
  docker_container:
    name: plex
    image: linuxserver/plex@sha256:8e2526182faf21f5b9264e8bb8f3946fd96b6de0a6dbcd925547a9e812d98a48
    volumes:
      - "{{ media_dir }}:/Media"
      - "{{ docker_path }}/plex/config:/config"
    network_mode: "host"
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: "docker"
    restart_policy: unless-stopped


# audiobookshelf

# airsonic

# vpn

# prowlarr

# transmission

# sonarr
- name: sonarr
  docker_container:
    name: sonarr
    image: linuxserver/sonarr@sha256:500af79ff1d83daee79143fd82d5d756bf0a33c048312a317a72ce747f62f0a9
    ports:
      - "8989:8989"
    volumes:
      - "{{ docker_path }}/sonarr/config:/config"
      - "{{ media_dir }}:/tv"
      - "{{ downloads_dir }}/torrents:/downloads"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "America/Los_Anegles"
    restart_policy: unless-stopped

# radarr
- name: radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr@sha256:8aa8c443dad68faedbed847cfdfa7205bd481b941d758ed98fa6d3c3d1fb1b37
    ports:
      - "7878:7878"
    volumes:
      - "{{ docker_path }}/radarr/config:/config"
      - "{{ media_dir }}:/movies"
      - "{{ downloads_dir }}/torrents:/downloads"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "America/Los_Anegles"
    restart_policy: unless-stopped

# tdarr
