---

# traefik
- name: traefik
  docker_container:
    name: traefik
    image: traefik:v2.10
    volumes:
      - "{{ docker_path }}/traefik/traefik.yml:/traefik.yml"
    ports:
      - "80:80"
      - "8080:8080"
    restart_policy: unless-stopped

# homer
- name: homer-dashboard
  docker_container:
    name: homer-dashboard
    image: b4bz/homer@sha256:23ef711ea0f5681f668930eae7661a8815184afd99885c387b0eef33fe6982b8
    volumes:
      - "{{ docker_path }}/homer:/www/assets"
    ports:
      - "8385:8080"
    restart_policy: unless-stopped

# kanboard
- name: kanboard
  docker_container:
    name: kanboard
    image: kanboard/kanboard@sha256:d3907466c5f063f918813c9a5d41b535d71a9d1a258b4f2eb93a65f633ad0a4b
    volumes: 
      - "{{ docker_path }}/kanboard/data:/var/www/app/data"
      - "{{ docker_path }}/kanboard/plugins:/var/www/app/plugins"
    ports:
      - "8765:8765"
    restart_policy: unless-stopped

# openbooks
- name: openbooks 
  docker_container:
    name: openbooks
    image: evanbuss/openbooks@sha256:3b3d34d8b77e8261df1f470e1ca8344c035e316a86667dc7c1ab2e768d6359f1
    volumes:
      - "{{downloads_dir}}:/books"
    ports:
      - "4567:80"
    command: ["--name", "iker_neptunus", "--persist", "-s", "irc.irchighway.net:9999"]
    restart_policy: unless-stopped

# plex
- name: plex
  docker_container:
    name: plex
    image: linuxserver/plex@sha256:8e2526182faf21f5b9264e8bb8f3946fd96b6de0a6dbcd925547a9e812d98a48
    volumes:
      - "{{ media_dir }}:/Media"
      - "{{ docker_path }}/plex/config:/config"
    network_mode: "host"
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: "docker"
    restart_policy: unless-stopped

# airsonic
- name: airsonic
  docker_container:
    name: airsonic
    image: linuxserver/airsonic@sha256:611c05dda8c8c7c86f5116e2343cf38f38fbb8595e90ba964e240f05f2746ef6
    ports:
      - "4040:4040"
    volumes:
      - "{{ media_dir }}/Media/Music:/media"
      - "{{ docker_path }}:/airsonic/config"
      - "{{ docker_path }}:/airsonic/playlists"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "{{ timezone}}"
    restart_policy: unless-stopped

# sonarr
- name: sonarr
  docker_container:
    name: sonarr
    image: linuxserver/sonarr@sha256:500af79ff1d83daee79143fd82d5d756bf0a33c048312a317a72ce747f62f0a9
    ports:
      - "8989:8989"
    volumes:
      - "{{ docker_path }}/sonarr/config:/config"
      - "{{ media_dir }}:/tv"
      - "{{ downloads_dir }}/torrents:/downloads"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped

# radarr
- name: radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr@sha256:8aa8c443dad68faedbed847cfdfa7205bd481b941d758ed98fa6d3c3d1fb1b37
    ports:
      - "7878:7878"
    volumes:
      - "{{ docker_path }}/radarr/config:/config"
      - "{{ media_dir }}:/movies"
      - "{{ downloads_dir }}/torrents:/downloads"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped

# node exporter
- name: node-exporter
  docker_container:
    name: node-exporter
    image: prom/node-exporter@sha256:40ba9ef2dc8d7564d76656feca7f679062d2df71653618211d38c0ec51ebc28c
    command: ["--path.rootfs=/host"]
    ports:
      - "9100:9100"
    volumes:
      - "/:/host:ro,rslave"
    restart_policy: unless-stopped

# promestheus
- name: promstheus
  docker_container:
    name: prometheus
    image: prom/prometheus@sha256:c5dd3503828713c4949ae1bccd1d8d69f382c33d441954674a6b78ebe69c3331
    ports:
      - "9090:9090"
    volumes:
      - "{{ docker_path }}/prometheus:/etc/prometheus"
    restart_policy: unless-stopped

- name: create network for grafana, loki, and promtail
  docker_network:
    name: loki

# grafana
- name: grafana
  docker_container:
    name: grafana
    image: grafana/grafana@sha256:80b7e6a6451036c604fb0cb9294dbb5b63058db80b1a3b838cb5f80cf7c8c362
    ports:
      - "3000:3000"
    networks:
      - name: "loki"
    restart_policy: unless-stopped

# loki
- name: loki
  docker_container:
    name: loki
    image: grafana/loki@sha256:bde9416a938f43d5c6e38f68aaea19b878184be79db2a6c0b6ec9a535053f5bf
    volumes:
      - "{{ docker_path }}/loki:/etc/loki"
    ports:
      - "3100:3100"
    command: 
      - ["--config.file=/etc/loki/loki-config.yml"]
    networks:
      - name: "loki"
    restart_policy: unless-stopped

# promtail
- name: promtail
  docker_container:
    name: promtail
    image: grafana/promtail@sha256:7fac20cf7240da82804217ba62821515c22c6097613f23a27b37cfa9338aab48
    volumes:
     - "{{ docker_path }}/promtail:/etc/promtail"
     - "/var/log:/var/log"
    command:
      - ["--config.file=/etc/promtail/promtail-config.yml"]
    networks:
      - name: "loki"
    restart_policy: unless-stopped

# vpn
# prowlarr
# transmission
# tdarr
