---

- name: create promtail volume
  docker_volume:
    name: promtail_data

- name: promtail container
  docker_container:
    name: promtail
    image: grafana/promtail:2.9.1
    volumes:
      - "promtail_data:/etc/promtail"
      - "/var/log:/var/log"
    restart_policy: unless-stopped

- name: node_exporter container
  docker_container:
    name: node_exporter
    image: prom/node-exporter@sha256:40ba9ef2dc8d7564d76656feca7f679062d2df71653618211d38c0ec51ebc28c
    command: ["--path.rootfs=/host"]
    ports:
      - "9100:9100"
    volumes:
      - "/:/host:ro,rslave"
    restart_policy: unless-stopped

- name: bind docker container
  docker_container:
    name: bind-dns
    image: ubuntu/bind9:latest
    volumes:
      - "/home/anthony/docker-volumes/bind-dns/config:/etc/bind"
      - "/home/anthony/docker-volumes/bind-dns/cache:/var/cache/bind"
      - "/home/anthony/docker-volumes/bind-dns/records:/var/lib/bind"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    env:
     BIND9_USER: 'root'
     TZ: "{{ timezone }}"
    restart_policy: unless-stopped

# duckdns
# - name: duckdns
#   docker_container:
#     name: duckdns
#     image: linuxserver/duckdns@sha256:15437356505cf8a7bf4633a4899d8e9b6c5a4b42604f0ca2f0e9948f0ffa0111
#     volumes:
#       - "/home/anthony/docker-volumes/duckdns/config:/config"
#     env:
#       PUID: "1000"
#       PGID: "1000"
#       TZ: "{{ timezone }}"
#       SUBDOMAINS: "{{ ddns_subdomains }}"
#       TOKEN: "{{ ddns_token }}"
#     restart_policy: unless-stopped

# wireguard
- name: wireguard
  docker_container:
    name: wireguard
    image: linuxserver/wireguard@sha256:3e22b4667589decf9f8f29f138691990b8177159568bb39ce907a801b363d32d
    ports:
      - "51820:51820/udp"
    volumes:
      - "/home/anthony/docker-volumes/wireguard/config:/config"
      - "/lib/modules:/lib/modules"
    env:
      PUID: "1000"
      PGID: "1000"
      SERVERURL: "mole-homelab.duckdns.org"
      PEERS: "desktop,laptop,phone,tablet"
      INTERNAL_SUBNET: 10.13.13.0/24
      TZ: "{{ timezone }}"
    capabilities:
      - net_admin
      - sys_module
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    restart_policy: unless-stopped

# mosquitto
- name: mosquitto
  docker_container:
    name: mosquitto
    image: eclipse-mosquitto:1.6.12
    ports:
      - "1883:1883"
    volumes:
      - "/home/anthony/docker-volumes/mosquitto/data:/data"
      - "/home/anthony/docker-volumes/mosquitto/config:/config"
      - "/home/anthony/docker-volumes/mosquitto/logs:/logs"
    env:
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped

# home assistant
- name: home-assistant
  docker_container:
    name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:2023.10
    network_mode: 'host'
    volumes:
      - "/home/anthony/docker-volumes/hass/config:/config"
    env:
      TZ: "{{ timezone }}"
    devices:
      - "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230525115147-if00:/dev/ttyACM0"
    restart_policy: unless-stopped
