---

- name: ensures bind config dir exists
  file:
    path: "/home/anthony/docker-volumes/bind-dns/config"
    state: directory

- name: copy bind config
  copy:
    src: "configs/named.conf"
    dest: "/home/anthony/docker-volumes/bind-dns/config/named.conf"

- name: copy zone config
  copy:
    src: "configs/homelab-lan.zone"
    dest: "/home/anthony/docker-volumes/bind-dns/config/homelab-lan.zone"

- name: ensure mosquitto dir exists
  file:
    path: "/home/anthony/docker-volumes/mosquitto/config"
    state: directory

- name: copy mosquitto config
  copy:
    src: "configs/mosquitto_config.conf"
    dest: "/home/anthony/docker-volumes/mosquitto/config/mosquitto.conf"
  become: true
