---

- name: ensures prometheus dir exists
  file:
    path: "{{ docker_path }}/prometheus"
    state: directory
    
- name: copy prometheus configuration
  ansible.builtin.copy:
    src: "configs/prometheus.yml"
    dest: "{{ docker_path }}/prometheus/prometheus.yml"

- name: ensures traefik dir exists
  file:
    path: "{{ docker_path }}/traefik"
    state: directory

- name: copy traefik configuration
  ansible.builtin.copy:
    src: "configs/traefik.yml"
    dest: "{{ docker_path }}/traefik/traefik.yml"

- name: ensures homer dir exists
  file:
    path: "{{ docker_path }}/homer"
    state: directory

- name: copy homer configuration
  ansible.builtin.copy:
    src: "configs/homer_config.yml"
    dest: "{{ docker_path }}/homer/config.yml"

- name: ensures loki dir exists
  file:
    path: "{{ docker_path }}/loki"
    state: directory
    
- name: copy loki configuration
  ansible.builtin.copy:
    src: "configs/loki-config.yml"
    dest: "{{ docker_path }}/loki/local-config.yml"

- name: ensures promtail dir exists
  file:
    path: "{{ docker_path }}/promtail"
    state: directory
    
- name: copy promtail configuration
  ansible.builtin.copy:
    src: "configs/promtail-config.yml"
    dest: "{{ docker_path }}/promtail/config.yml"
