---

- name: wordle-clone
  docker_container:
    name: wordle-clone
    image: anthonymolinari/word-guess@sha256:3b3c923c22d05094d8f80d6e1998387857dadc9cf566d91920782b46f631246c
    ports:
      - "3210:3000"
    restart_policy: unless-stopped