---

- name: wordle-clone
  docker_container:
    name: wordle-clone
    image: anthonymolinari/word-guess@sha256:3b3c923c22d05094d8f80d6e1998387857dadc9cf566d91920782b46f631246c
    ports:
      - "3210:3000"
    restart_policy: unless-stopped

- name: react-pentago
  docker_container:
    name: react-pentago
    image: anthonymolinari/react-pentago@sha256:60d83a4339e3c5b05aad5ee3dc02890dc53cc1c807c1992689ab8451a923b7fd
    ports:
      - "3211:3000"
    restart_policy: unless-stopped