---

- name: wordle-clone
  docker_container:
    name: wordle-clone
    image: anthonymolinari/word-guess@sha256:3b3c923c22d05094d8f80d6e1998387857dadc9cf566d91920782b46f631246c
    ports:
      - "3210:3000"
    restart_policy: unless-stopped

- name: react-pentago
  docker_container:
    name: react-pentago
    image: anthonymolinari/react-pentago@sha256:5cac89f6fe2905ef3471fb6cbe8925feb166bc4e98f273d39870832aca42d980
    ports:
      - "3211:3000"
    restart_policy: unless-stopped