---

- name: create promtail volume
  docker_volume:
    name: promtail_data

- name: promtail container
  docker_container:
    name: promtail
    image: grafana/promtail:2.9.1
    volumes:
      - "promtail_data:/etc/promtail"
      - "/var/log:/var/log"
    restart_policy: unless-stopped

- name: node_exporter container
  docker_container:
    name: node_exporter
    image: prom/node-exporter@sha256:40ba9ef2dc8d7564d76656feca7f679062d2df71653618211d38c0ec51ebc28c
    command: ["--path.rootfs=/host"]
    volumes:
      - "/:/host:ro,rslave"
    ports:
      - "9100:9100"
    restart_policy: unless-stopped

- name: wordle-clone
  docker_container:
    name: wordle-clone
    image: anthonymolinari/word-guess@sha256:3b3c923c22d05094d8f80d6e1998387857dadc9cf566d91920782b46f631246c
    ports:
      - "3210:3000"
    restart_policy: unless-stopped