---

- name: create network for all services
  docker_network:
    name: kestra

- name: postgres-kestra
  docker_container:
    name: postgres-kestra
    image: postgres
    ports:
    volumes:
      - "{{ docker_path }}/postgres-kestra/data:/var/lib/postgressql/data"
    networks:
      - name: "kestra"
    env:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    restart_policy: unless-stopped

- name: kestra-server
  docker_container:
    name: kestra-server
    image: kestra/kestra:latest-full
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - "{{ docker_path }}/kestra/"
    networks:
      - name: "kestra"
    command: ["server", "standalone", "--worker-thread=128"]
    restart_policy: unless-stopped




