---

- name: create network for all services
  docker_network:
    name: automation

# traefik 
- name: traefik reverse proxy
  docker_container:
    name: traefik
    image: traefik:v2.11
    ports:
      - "80:80"
      - "443:443"
      - "81:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["--api.insecure=true", "--providers.docker"]
    networks:
      - name: "automation"
    restart_policy: unless-stopped

# kestra standalone
- name: kestra-server
  docker_container:
    name: kestra
    image: kestra/kestra:0.16.7-full # add version tag
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_path }}/kestra/data:/app/data"
      - "{{ docker_path }}/kestra/tasks:/tmp"
    command: ["server", "local"]
    network:
      - name: "automation"
    labels:
      traefik.http.routers.kestra.rule: "Host(`kestra.homelab.lan`)"
    restart_policy: unless-stopped

# secrets-api
- name: secrets-api
  docker_container:
    name: secrets-api
    image: anthonymolinari/secrets-api:v0.2.0
    ports:
      - "3210:3210"
    volumes:
      - "{{ docker_path }}/secrets-api/data:/data"
    env:
      - ""
    network:
      - name: "automation"
    labels:
      traefik.http.routers.secrets-api.rule: "Host(`api.secrets.homelab.lan`)"
    restart_policy: unless-stopped
