---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Anthony's Homelab"
subtitle: "Homer"
logo: "assets/tools/server.png"

header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

links:
  - name: "Personal Github"
    icon: "fab fa-github"
    url: "https://github.com/anthonymolinari"
  - name: "Portfolio Site"
    icon: "fab fa-browser"
    url: "https://anthonymolinari.dev"
  - name: "Awsome-Selfhosted"
    icon: "fab fa-github"
    url: "https://github.com/awesome-selfhosted/awesome-selfhosted"
  - name: "r/selfhosted"
    icon: "fab fa-reddit"
    url: "https://www.reddit.com/r/selfhosted/"
  - name: "Logs"
    url: "http://10.32.1.10:7373/logs/"
  - name: "scripts"
    url: "http://10.32.1.10:7373/scripts/"

services:
  - name: "Network"
    icon: "fas fa-network-wired"
    items:
      - name: "OpenWRT"
        logo: "assets/tools/openwrt.png"
        url: "http://10.32.1.1"
        tag: "Firewall/Router"
        subtitle: ""
      - name: "Omada Controller"
        logo: "assets/tools/omada.png"
        url: "http://10.32.1.8:8043"
        tag: "AP CDN"
        subtitle: ""
      - name: "Nginx Proxy Manager"
        logo: "assets/tools/nginxproxymanager.png"
        url: "http://10.32.1.10:81"
        tag: ""
        subtitle: ""
      - name: "Proxmox-network-server"
        logo: "assets/tools/proxmox.png"
        url: "https://10.32.1.30:8006"
        subtitle: "Open-source Linux Hypervisor"
        tag: "Hypervisor"
      - name: "Proxmox-lab"
        logo: "assets/tools/proxmox.png"
        url: "https://10.32.1.6:8006"
        subtitle: "Open-source Linux Hypervisor"
        tag: "Hypervisor"
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Tautulli"
        logo: "assets/tools/tautulli.png"
        url: "http://tautulli.lan/"
        subtitle: "Stats for Plex"
        tag: "Media Server Metrics"
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        url: "http://portainer.lan"
        tag: "docker"
        subtitle: "Container Management Tool"
      - name: "Home Assistant"
        logo: "assets/tools/home-assistant.png"
        url: "http://10.32.1.10:8123"
        subtitle: "Home Automation"
        tag: ""
      - name: "Jenkins"
        logo: "assets/tools/jenkins.png"
        url: "http://10.32.1.10:8080"
        subtitle: "CI/CD Platform"
        tag: "devops"
      - name: "Kanboard"
        logo: "assets/tools/kanboard.png"
        url: "http://10.32.1.10:8765"
        subtitle: ""
        tag: "devops"
      - name: "OpenBooks"
        logo: "assets/tools/openbooks.png"
        url: "http://10.32.1.10:4567"
        subtitle: "IIRC eBook Client"
        tag: "ebook dowloader"
  - name: "Media"
    icon: "fas fa-play-circle"
    items:
      - name: "Plex"
        logo: "assets/tools/plex.png"
        url: "http://plex.lan"
        subtitle: "Self-Hosted Media Streaming"
        tag: "Streaming"
      - name: "Airsonic"
        logo: "assets/tools/airsonic.png"
        url: "http://10.32.1.10:4040"
        subtitle: "Slef-Hosted Music Streaming"
        tag: "Streaming"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.png"
        url: "http://sonarr.lan"
        subtitle: "Internet DVR for TV"
        tag: "Torrent"
      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        url: "http://radarr.lan"
        subtitle: "Internet DVR for Movies"
        tag: "Torrent"
      - name: "Prowlarr"
        logo: "assets/tools/prowlarr.png"
        url: "http://prowlarr.lan/"
        subtitle: "Torrent Indexer for Servarr Applications"
        tag: "Torrent"
      - name: "Transmission"
        logo: "assets/tools/transmission.png"
        url: "http://10.32.1.10:9091/"
        subtitle: "Torrent Client"
        tag: "Torrent"
      - name: "Tdarr"
        logo: "assets/tools/tdarr.png"
        url: "http://tdarr.lan/"
        subtitle: "Automated Transcoding Tool"
