---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Anthony's Homelab"
subtitle: "Homer"
logo: "assets/tools/server.png"

header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

links:
  - name: "Personal Github"
    icon: "fab fa-github"
    url: "https://github.com/anthonymolinari"
  - name: "Portfolio Site"
    icon: "fab fa-browser"
    url: "https://anthonymolinari.dev"
  - name: "Awsome-Selfhosted"
    icon: "fab fa-github"
    url: "https://github.com/awesome-selfhosted/awesome-selfhosted"
  - name: "r/selfhosted"
    icon: "fab fa-reddit"
    url: "https://www.reddit.com/r/selfhosted/"

services:
  - name: "Network"
    icon: "fas fa-network-wired"
    items:
      - name: "OpenWRT"
        logo: "assets/tools/openwrt.png"
        url: "http://10.32.1.1"
        tag: "Firewall/Router"
        subtitle: ""
      - name: "Omada Controller"
        logo: "assets/tools/omada.png"
        url: "http://omada.homelab.lan"
        tag: "AP CDN"
        subtitle: ""
      - name: "Proxmox-network-server"
        logo: "assets/tools/proxmox.png"
        url: "https://10.32.1.30:8006"
        subtitle: "Open-source Linux Hypervisor"
        tag: "Hypervisor"
      - name: "Proxmox-lab"
        logo: "assets/tools/proxmox.png"
        url: "https://10.32.1.6:8006"
        subtitle: "Open-source Linux Hypervisor"
        tag: "Hypervisor"
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.png"
        url: "http://nextcloud.homelab.lan"
        tag: ""
        subtitle: "Personal Cloud"
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        url: "http://grafana.homelab.lan"
        tag: "Metrics & Logging"
        subtitle: ""
      - name: "Prometheus"
        logo: "assets/tools/prometheus.png"
        url: "http://prometheus.homelab.lan"
        tag: "Metrics & Logging"
        subtitle: "Timeseries Database For Metrics"
      - name: "Home Assistant"
        logo: "assets/tools/home-assistant.png"
        url: "http://hass.homelab.lan"
        subtitle: "Home Automation"
        tag: "Automation"
      - name: "Semaphore"
        logo: "assets/tools/ansiblesemaphore.png"
        url: "http://semaphore.homelab.lan"
        subtitle: "A Moder UI For Ansible"
        tag: "Automation"
  - name: "Media"
    icon: "fas fa-play-circle"
    items:
      - name: "Plex"
        logo: "assets/tools/plex.png"
        url: "http://plex.homelab.lan"
        subtitle: "Self-Hosted Media Streaming"
        tag: "Streaming"
      - name: "OpenBooks"
        logo: "assets/tools/openbooks.png"
        url: "http://openbooks.homelab.lan"
        subtitle: "IIRC eBook Client"
        tag: "ebook dowloader"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.png"
        url: "http://sonarr.homelab.lan"
        subtitle: "Internet DVR for TV"
        tag: "Torrent"
      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        url: "http://radarr.homelab.lan"
        subtitle: "Internet DVR for Movies"
        tag: "Torrent"
      - name: "Prowlarr"
        logo: "assets/tools/prowlarr.png"
        url: "http://prowlarr.homelab.lan/"
        subtitle: "Torrent Indexer for Servarr Applications"
        tag: "Torrent"
      - name: "Transmission"
        logo: "assets/tools/transmission.png"
        url: "http://transmission.homelab.lan/"
        subtitle: "Torrent Client"
        tag: "Torrent"
      - name: "Tdarr"
        logo: "assets/tools/tdarr.png"
        url: "http://tdarr.homelab.lan/"
        subtitle: "Automated Transcoding Tool"
