---

# install packages
- name: install packages
  package: 
    name: 
      - tmux
      - ranger
      - git 
      - curl
    state: present

# install neovim 


# get tmux config
- name: clone tmux config
  shell: |
    git clone https://github.com/anthonymolinari/dot-files-tmux.git ~/.config/tmux 
    git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

# get nvim config
- name: clone nvim config
  shell: |
    git clone https://github.com/anthonymolinari/dot-files-nvim.git ~/.config/nvim
    git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
