// non-container related stuff will run from here


// setup files shares


// sync cron scripts from github


// sync nvim config from github


// sync ranger config from github


// update contents of cron schedule 
