---

- name: create traefik network
  docker_network:
    name: "traefik"

# traefik 
- name: traefik reverse proxy
  docker_container:
    name: traefik
    image: traefik:v2.11
    ports:
      - "80:80"
      - "443:443"
      - "81:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["--api.insecure=true", "--providers.docker"]
    networks:
      - name: "traefik"
    restart_policy: unless-stopped

- name: wordle-clone
  docker_container:
    name: wordle-clone
    image: anthonymolinari/word-guess@sha256:b6cf2e2cda05764553ba8be3f9d25ed95645f936c808e255169232fc16174be0
    ports:
      - "3210:3000"
    restart_policy: unless-stopped

- name: react-pentago
  docker_container:
    name: react-pentago
    image: anthonymolinari/react-pentago@sha256:c3e15f18f0bf987e5f91c42b77f30310e975aa2d629feedf27e4bec858201ae6
    ports:
      - "3211:3000"
    restart_policy: unless-stopped

