name: deploy shared tasks

on:
  workflow_dispatch:
push:
  branches: ['main']
  paths:
    - 'tasks/shared_tasks/**'
    - 'configs/shared/**'
    - 'group_vars/all/**'
    - 'hosts'
    - 'run_shared_tasks.yml'
       

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        
      - name: run playbook
        run: ansible-playbook run_shared_tasks.yml --vault-password-file='${{ secrets.VUALT_PASS_FILE }}'

