name: deploy

on:
  push: 
    branches: ['main']
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: run playbook
        run: ansible-playbook run.yml
        env:
          ANSIBLE_VAULT_PASSWORD: S{{ secrets.VAULT_PASS }}
