name: deploy

on:
  push: 
    branches: ['main']
    paths: 
      - 'tasks/**'
      - 'configs/**'
      - 'group_vars/**'
      - 'templates/**'
      - 'run.yml'
      - 'dependencies.yml'
      - 'hosts'
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: run playbook
        run: ansible-playbook run.yml --vault-password-file='${{ secrets.VAULT_PASS_FILE }}'
