name: tests

on:
  pull_request:
    branches: ['*']

jobs:
  syntax_check:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: ansible syntax validation
        run: ansible-playbook run_main_tasks.yml --syntax-check

      - name: dry-run
        run: ansible-playbook run_main_tasks.yml --check --vault-password-file='${{ secrets.VAULT_PASS_FILE }}'

      - name: ansible syntax validation
        run: ansible-playbook run_network_tasks.yml --syntax-check

      - name: dry-run
        run: ansible-playbook run_network_tasks.yml --check --vault-password-file='${{ secrets.VAULT_PASS_FILE }}'

      - name: ansible syntax validation
        run: ansible-playbook run_shared_tasks.yml --syntax-check

      - name: dry-run
        run: ansible-playbook run_shared_tasks.yml --check --vault-password-file='${{ secrets.VAULT_PASS_FILE }}'

